image: python:3.6

cache:
  paths:
  - ~/.cache/pip/

before_script:
  - pip install tox coverage

test:
  script: tox

test_coverage:
  script:
    - coverage run --source='.' manage.py test --noinput -v 3
    - coverage report --skip-covered | grep TOTAL
