language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
evn:
  - DJANGO=1.4
  - DJANGO=1.5
# command to install dependencies
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install -q -e . --use-mirrors"
# command to run tests
script: python setup.py test 
