language: python
python:
  - "2.7"
  - "3.4"
env:
  matrix:
    - DJANGO_VERSION="django>=1.7,<1.8"
    - DJANGO_VERSION="django>=1.8,<1.9"
install:
  - pip install -e . -r requirements.txt $DJANGO_VERSION
  - pip install coveralls
script: coverage run --source=report_builder manage.py test
after_success:
  coveralls
sudo: false
